//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warsofcars.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("warsofcars.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _2010_Ferrari_458_Italia_2 {
            get {
                object obj = ResourceManager.GetObject("2010-Ferrari-458-Italia-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2010_Ferrari_458_Italia_21 {
            get {
                object obj = ResourceManager.GetObject("2010-Ferrari-458-Italia-21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2010_Ferrari_458_Italia_22 {
            get {
                object obj = ResourceManager.GetObject("2010-Ferrari-458-Italia-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap araba_0001 {
            get {
                object obj = ResourceManager.GetObject("araba_0001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bigicon_linechart {
            get {
                object obj = ResourceManager.GetObject("bigicon-linechart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BMW_Deri_Isikli_koruklu_vites_Topuzu__145807216_0 {
            get {
                object obj = ResourceManager.GetObject("BMW-Deri-Isikli-koruklu-vites-Topuzu__145807216_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BMW_Deri_Isikli_koruklu_vites_Topuzu__145807216_01 {
            get {
                object obj = ResourceManager.GetObject("BMW-Deri-Isikli-koruklu-vites-Topuzu__145807216_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BMW_Deri_Isikli_koruklu_vites_Topuzu__45807216_0 {
            get {
                object obj = ResourceManager.GetObject("BMW-Deri-Isikli-koruklu-vites-Topuzu__45807216_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bugatti_veyron_14090 {
            get {
                object obj = ResourceManager.GetObject("bugatti-veyron_14090", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bugatti_veyron_140901 {
            get {
                object obj = ResourceManager.GetObject("bugatti-veyron_140901", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ford_Mustang_Eleanor_Body_Kit_2 {
            get {
                object obj = ResourceManager.GetObject("Ford-Mustang-Eleanor-Body-Kit-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ford_Mustang_Eleanor_Body_Kit_21 {
            get {
                object obj = ResourceManager.GetObject("Ford-Mustang-Eleanor-Body-Kit-21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_8017_lamborghini_murcielago_lp640_1024_768_0_1__1_ {
            get {
                object obj = ResourceManager.GetObject("image_8017_lamborghini_murcielago_lp640_1024_768_0_1__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_8017_lamborghini_murcielago_lp640_1024_768_0_1__1_1 {
            get {
                object obj = ResourceManager.GetObject("image_8017_lamborghini_murcielago_lp640_1024_768_0_1__1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok4 {
            get {
                object obj = ResourceManager.GetObject("ok4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap post_2589_1215376213 {
            get {
                object obj = ResourceManager.GetObject("post-2589-1215376213", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w50kp2 {
            get {
                object obj = ResourceManager.GetObject("w50kp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap w50kp21 {
            get {
                object obj = ResourceManager.GetObject("w50kp21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WC_Tanıtım {
            get {
                object obj = ResourceManager.GetObject("WC Tanıtım", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
